// export { default as Head } from './head';
export { default as Email } from './email';
export { default as Layout } from './layout';
export { default as Loader } from './loader';
export { default as Menu } from './menu';
export { default as Nav } from './nav';
export { default as About } from './sections/about';
export { default as Code } from './sections/code';
export { default as Contact } from './sections/contact';
export { default as Hero } from './sections/hero';
export { default as Wood } from './sections/wood';
export { default as Work } from './sections/work';
export { default as Side } from './side';
export { default as Social } from './social';
